namespace FudgeCore {
  /**
   * The codes sent from a standard english keyboard layout
   */
  export enum KEYBOARD_CODE {
    A = "KeyA",
    B = "KeyB",
    C = "KeyC",
    D = "KeyD",
    E = "KeyE",
    F = "KeyF",
    G = "KeyG",
    H = "KeyH",
    I = "KeyI",
    J = "KeyJ",
    K = "KeyK",
    L = "KeyL",
    M = "KeyM",
    N = "KeyN",
    O = "KeyO",
    P = "KeyP",
    Q = "KeyQ",
    R = "KeyR",
    S = "KeyS",
    T = "KeyT",
    U = "KeyU",
    V = "KeyV",
    W = "KeyW",
    X = "KeyX",
    Y = "KeyY",
    Z = "KeyZ",
    ESC = "Escape",
    ZERO = "Digit0",
    ONE = "Digit1",
    TWO = "Digit2",
    THREE = "Digit3",
    FOUR = "Digit4",
    FIVE = "Digit5",
    SIX = "Digit6",
    SEVEN = "Digit7",
    EIGHT = "Digit8",
    NINE = "Digit9",
    MINUS = "Minus",
    EQUAL = "Equal",
    BACKSPACE = "Backspace",
    TABULATOR = "Tab",
    BRACKET_LEFT = "BracketLeft",
    BRACKET_RIGHT = "BracketRight",
    ENTER = "Enter",
    CTRL_LEFT = "ControlLeft",
    SEMICOLON = "Semicolon",
    QUOTE = "Quote",
    BACK_QUOTE = "Backquote",
    SHIFT_LEFT = "ShiftLeft",
    BACKSLASH = "Backslash",
    COMMA = "Comma",
    PERIOD = "Period",
    SLASH = "Slash",
    SHIFT_RIGHT = "ShiftRight",
    NUMPAD_MULTIPLY = "NumpadMultiply",
    ALT_LEFT = "AltLeft",
    SPACE = "Space",
    CAPS_LOCK = "CapsLock",
    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    PAUSE = "Pause",
    SCROLL_LOCK = "ScrollLock",
    NUMPAD7 = "Numpad7",
    NUMPAD8 = "Numpad8",
    NUMPAD9 = "Numpad9",
    NUMPAD_SUBTRACT = "NumpadSubtract",
    NUMPAD4 = "Numpad4",
    NUMPAD5 = "Numpad5",
    NUMPAD6 = "Numpad6",
    NUMPAD_ADD = "NumpadAdd",
    NUMPAD1 = "Numpad1",
    NUMPAD2 = "Numpad2",
    NUMPAD3 = "Numpad3",
    NUMPAD0 = "Numpad0",
    NUMPAD_DECIMAL = "NumpadDecimal",
    PRINT_SCREEN = "PrintScreen",
    INTL_BACK_SLASH = "IntlBackSlash",
    F11 = "F11",
    F12 = "F12",
    NUMPAD_EQUAL = "NumpadEqual",
    F13 = "F13",
    F14 = "F14",
    F15 = "F15",
    F16 = "F16",
    F17 = "F17",
    F18 = "F18",
    F19 = "F19",
    F20 = "F20",
    F21 = "F21",
    F22 = "F22",
    F23 = "F23",
    F24 = "F24",
    KANA_MODE = "KanaMode",
    LANG2 = "Lang2",
    LANG1 = "Lang1",
    INTL_RO = "IntlRo",
    CONVERT = "Convert",
    NON_CONVERT = "NonConvert",
    INTL_YEN = "IntlYen",
    NUMPAD_COMMA = "NumpadComma",
    UNDO = "Undo",
    PASTE = "Paste",
    MEDIA_TRACK_PREVIOUS = "MediaTrackPrevious",
    CUT = "Cut",
    COPY = "Copy",
    MEDIA_TRACK_NEXT = "MediaTrackNext",
    NUMPAD_ENTER = "NumpadEnter",
    CTRL_RIGHT = "ControlRight",
    AUDIO_VOLUME_MUTE = "AudioVolumeMute",
    LAUNCH_APP2 = "LaunchApp2",
    MEDIA_PLAY_PAUSE = "MediaPlayPause",
    MEDIA_STOP = "MediaStop",
    EJECT = "Eject",
    AUDIO_VOLUME_DOWN = "AudioVolumeDown",
    VOLUME_DOWN = "VolumeDown",
    AUDIO_VOLUME_UP = "AudioVolumeUp",
    VOLUME_UP = "VolumeUp",
    BROWSER_HOME = "BrowserHome",
    NUMPAD_DIVIDE = "NumpadDivide",
    ALT_RIGHT = "AltRight",
    HELP = "Help",
    NUM_LOCK = "NumLock",
    HOME = "Home",
    ARROW_UP = "ArrowUp",
    ARROW_RIGHT = "ArrowRight",
    ARROW_DOWN = "ArrowDown",
    ARROW_LEFT = "ArrowLeft",
    END = "End",
    PAGE_UP = "PageUp",
    PAGE_DOWN = "PageDown",
    INSERT = "Insert",
    DELETE = "Delete",
    META_LEFT = "Meta_Left",
    OS_LEFT = "OSLeft",
    META_RIGHT = "MetaRight",
    OS_RIGHT = "OSRight",
    CONTEXT_MENU = "ContextMenu",
    POWER = "Power",
    BROWSER_SEARCH = "BrowserSearch",
    BROWSER_FAVORITES = "BrowserFavorites",
    BROWSER_REFRESH = "BrowserRefresh",
    BROWSER_STOP = "BrowserStop",
    BROWSER_FORWARD = "BrowserForward",
    BROWSER_BACK = "BrowserBack",
    LAUNCH_APP1 = "LaunchApp1",
    LAUNCH_MAIL = "LaunchMail",
    LAUNCH_MEDIA_PLAYER = "LaunchMediaPlayer",

    //mac brings this buttton
    FN = "Fn", //no event fired actually

    //Linux brings these
    AGAIN = "Again",
    PROPS = "Props",
    SELECT = "Select",
    OPEN = "Open",
    FIND = "Find",
    WAKE_UP = "WakeUp",
    NUMPAD_PARENT_LEFT = "NumpadParentLeft",
    NUMPAD_PARENT_RIGHT = "NumpadParentRight",

    //android
    SLEEP = "Sleep"
  }

  export enum KEYBOARD_CODE_DE {
    Z = KEYBOARD_CODE.Y,
    Y = KEYBOARD_CODE.Z,
    Ö = KEYBOARD_CODE.SEMICOLON,
    Ä = KEYBOARD_CODE.QUOTE,
    Ü = KEYBOARD_CODE.BRACKET_LEFT,
    HASH = KEYBOARD_CODE.BACKSLASH,
    PLUS = KEYBOARD_CODE.BRACKET_RIGHT,
    ß = KEYBOARD_CODE.MINUS,
    ACUTE = KEYBOARD_CODE.EQUAL,
    LESS_THAN = KEYBOARD_CODE.INTL_BACK_SLASH,
    MINUS = KEYBOARD_CODE.SLASH
  }

  /* 
  Firefox can't make use of those buttons and Combinations:
  SINGELE_BUTTONS:
   Druck,
  COMBINATIONS:
   Shift + F10, Shift + Numpad5,
   CTRL + q, CTRL + F4,
   ALT + F1, ALT + F2, ALT + F3, ALT + F7, ALT + F8, ALT + F10
  Opera won't do good with these Buttons and combinations:
  SINGLE_BUTTONS:
   Float32Array, F11, ALT,
  COMBINATIONS:
   CTRL + q, CTRL + t, CTRL + h, CTRL + g, CTRL + n, CTRL + f 
   ALT + F1, ALT + F2, ALT + F4, ALT + F5, ALT + F6, ALT + F7, ALT + F8, ALT + F10
   */
}