@startuml FUDGE-Core
skinparam monochrome true
skinparam componentStyle uml2
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam handwritten false

'page 2x2
left to right direction
'top to bottom direction

package Fudge <<Rectangle>>{
  ' gl2: WebGL2RenderingContext

  package "Engine" <<Folder>> {
    file "Node" {
      class Node extends EventTarget {
        - parent: Node | null
        - children: Node[]
        - components: MapClassToComponents
      }
      interface MapClassToComponents{
        [className: string]: Component[]
      }
      interface MapStringToNode {
        [key: string]: Node
      }
    }
    class Color {
      // to be implemented
    }
    class Material {
      - name: string;
      - shaderClass: typeof Shader;
      - color: Vector3;
      - textureEnabled: boolean;
      - textureSource: string;
    }
    file "Viewort" {
      interface Rectangle {
        x: number;
        y: number;
        width: number;
        height: number;
      }
      class Viewport extends EventTarget {
        + name: string
        + camera: ComponentCamera
        + branch: Node
        + rectSource: Rectangle
        + rectDestination: Rectangle
        - canvas: HTMLCanvasElement
        - crc2: CanvasRenderingContext2D
      }
    }

    file "Event"{
      interface MapEventTypeToListener {
        [eventType: string]: EventListener[];
      }

      enum EVENT

      class EventTargetStatic extends EventTarget {
        #{static} targetStatic: EventTargetStatic
      }
    }

    class Loop extends EventTargetStatic {
      - {static} running: boolean = false
      + {static} start(): void
    }
  }

  package "WebGL" <<Folder>> {
    interface NodeReferences {
      shader: typeof Shader;
      material: Material;
      mesh: Mesh;
      doneTransformToWorld: boolean;
    }
    interface BufferSpecification {
      size: number
      dataType: number
      normalize: boolean
      stride: number
      offset: number
    }
    class WebGLReference<T> {
      private reference: T;
      private count: number = 0;
    }
    class WebGL extends WebGLApi {
      - {static} programs: Map<typeof Shader, WebGLReference<ShaderInfo>>;
      - {static} parameters: Map<Material, WebGLReference<MaterialInfo>>;
      - {static} buffers: Map<Mesh, WebGLReference<BufferInfo>>;
      - {static} nodes: MapNodeToNodeReferences;
    }

    interface ShaderInfo {
      program: WebGLProgram;
      attributes: MapNameToValue;
      uniforms: MapNameToUniformLocation;
    }
    interface BufferInfo {
      buffer: WebGLBuffer;
      target: number;
      specification: BufferSpecification;
      vertexCount: number;
    }
    interface MaterialInfo {
      vao: WebGLVertexArrayObject;
      color: Vector3;
    }
    class WebGLApi {
      + {static} crc3: WebGL2RenderingContext;
      + {static} canvas: HTMLCanvasElement;
      + {static} rectViewport: Rectangle;
    }
  }

  package "Browser" <<Cloud>> {
    class EventTarget
    class WebGL2RenderingContext
    class HTMLCanvasElement
    class CanvasRenderingContext2D
  }
  package "Transfer" <<Folder>> {
    file "Serializer" {
      interface Serializable {
        serialize(): Serialization;
        deserialize(_serialization: Serialization): Serializable;
      }
      interface Serialization {
        [type: string]: General;
      }
      class Serializer {
        {static} + serialize(_object: Serializable): Serialization
        {static} + deserialize(_serialization: Serialization): Serializable
      }
    }
    file "Mutable" {
      interface MutatorAttributeTypes
      interface Mutator

      interface MutatorForAnimation extends Mutator
      interface MutatorForUserInterface extends Mutator
      class Mutable extends EventTarget {
        + getMutator(): Mutator
        + getMutatorForAnimation(): MutatorForAnimation
        + getMutatorForUserInterface(): MutatorForUserInterface
        + getMutatorAttributeTypes(_mutator: Mutator): MutatorAttributeTypes
        + updateMutator(_mutator: Mutator): void
        # mutate(_mutator: Mutator): void
      }
    }
  }

  package "Components" <<Folder>> {
    abstract class Component extends Mutable {
      # singleton: boolean
      - container: Node | null
      - active: boolean
    }

    class ComponentCamera extends Component {
      - orthographic: boolean
      - projectionMatrix: Matrix4x4
      - fieldOfView: number
      - aspectRatio: number
      - backgroundColor: Vector3
      - backgroundEnabled: boolean
    }
    class ComponentMaterial extends Component {
      - material: Material;
    }
    class ComponentMesh extends Component {
      - mesh: Mesh
    }
    class ComponentPivot extends Component {
      + local: Matrix4x4
    }
    class ComponentTransform extends ComponentPivot {
      + world: Matrix4x4
    }
    class ComponentScript extends Component {
    }
  }

  package "Meshes" <<Folder>> {
    class Mesh {
      # vertices: Float32Array
    }
    class MeshCube extends Mesh {
      + width: number;
      + height: number;
      + depth: number;
    }
  }

  package "Math" <<Folder>> {
    class Vector3 {
      - data: number[]
      // to be refactored, components as x,y,z numbers
    }
    class Matrix3x3 {
      + data: number[]
    }
    class Matrix4x4 extends Mutable {
      + data: Float32Array
    }
  }

  package "Shader" << Folder>> {
    abstract class Shader {
      + {static} loadVertexShaderSource(): string
      + {static} loadFragmentShaderSource(): string
    }
    class ShaderBasic extends Shader {
    }
    class ShaderTexture extends Shader {
    }
  }

  ' Associations
  Mesh --() Serializable
  Component --() Serializable
  Node  --() Serializable
  Matrix4x4 --() Serializable
  Serializer  -(0- Serializable
  Serializer  -(0- Serialization

  Mutable -(0- Mutator
  Mutable -(0- MutatorAttributeTypes

  Node "0..1 parent" o-left- "n children" Node
  Node "1 container" o-- "n components" Component

  ComponentMesh "n" --> "1" Mesh
  ComponentPivot -->"1" Matrix4x4
  ComponentTransform -->"1" Matrix4x4
  ComponentMaterial "n" --> "1" Shader : refers >
  Shader "n"-->"1" Material : uses >
  Viewport -->"1 root" Node : displays >
  Viewport -->"1 camera" ComponentCamera : look through >
  Viewport "n" --> "1" CanvasRenderingContext2D : renders >
  Viewport "n" -> "1" WebGL : feeds data and retrieves image >
  WebGL "1" -> "1" WebGL2RenderingContext : store buffers\nrender offscreen >
  WebGL "1" o--> "n" NodeReferences : keeps >
  WebGL "1" o--> "n" WebGLReference : keeps >
  WebGLReference "1" --> "1" ShaderInfo : shader uses >
  WebGLReference "1" --> "1" BufferInfo : mesh uses >
  WebGLReference "1" --> "1" MaterialInfo : material uses >
  BufferInfo --> BufferSpecification : provides >

  'improve layout
  'Node -[hidden]- Serializable
  'Component -[hidden]- Serializable
  'Serializer --[hidden]-- Mutable
  'Mutable --[hidden]-- Component
  'Viewport -[hidden]- ComponentCamera
  'Engine -[hidden]- Meshes
  'Engine -[hidden]- Browser
  'Loop -[hidden]- Material
  'Meshes --[hidden]up-- Shader
  'EventTarget -[hidden] EventTargetStatic
  @enduml
