/**
 * Goes through all GLSL-Shaders in this folder and turns them into "TypeScript-Shaders".
 * A vertex-shader (.vert) and a fragment-shader(.frag) with the same file name are required
 * @authors Luis Keck, HFU, 2021
 */
import * as fs from "fs";
import { argv } from "process";

let json = JSON.parse(fs.readFileSync(argv[2], { encoding: 'utf8' }));
// console.log(json);

for (let name in json) {
  console.log(name);
  let shader = json[name];
  let code = "";

  code += `/** Code generated by CompileShaders.mjs using the information in ${argv[2]} */\n\n`;

  code += `export abstract class ${name} extends Shader {\n`;
  code += `  public static readonly iSubclass: number = Shader.registerSubclass(${name});\n\n`;

  if (shader.coat)
    code += `  public static getCoat(): typeof Coat { return ${shader.coat}; }\n\n`;

  let vertex = fs.readFileSync(shader.vertex, { encoding: 'utf8' })
  code += "  public static getVertexShaderSource(): string { \n";
  code += "return `";
  code += vertex;
  code += "\n`; }\n\n";
  
  let fragment = fs.readFileSync(shader.fragment, { encoding: 'utf8' })
  code += "  public static getFragmentShaderSource(): string { \n";
  code += "return `";
  code +=  fragment;
  code += "\n`; }\n";

  code += `}`;

  if (shader.namespace) {
    code = `namespace ${shader.namespace} {\n` + code + `\n}`;
  }

  fs.writeFileSync(shader.outdir + "/" + name + ".ts", code);
}
