var MiniScene;
(function (MiniScene) {
    var ƒ = Fudge;
    window.addEventListener("DOMContentLoaded", init);
    let node;
    let camera;
    let viewPort;
    function init() {
        ƒ.GLUtil.initializeContext();
        let shdBasic = new ƒ.ShaderBasic();
        let mtrRed = new ƒ.Material("Red", new ƒ.Vector3(255, 0, 0), shdBasic);
        let cmpMesh = new ƒ.ComponentMesh();
        cmpMesh.initialize(new ƒ.MeshCube(50, 50, 50).Positions);
        let cmpMaterial = new ƒ.ComponentMaterial();
        cmpMaterial.initialize(mtrRed);
        let cmpTransform = new ƒ.ComponentTransform();
        node = new ƒ.Node("Node");
        node.addComponent(cmpMesh);
        node.addComponent(cmpMaterial);
        node.addComponent(cmpTransform);
        cmpTransform.scaleX(2);
        camera = new ƒ.Node("Camera");
        cmpTransform = new ƒ.ComponentTransform();
        cmpTransform.translate(100, 100, 500);
        cmpTransform.lookAt(node.transform.position);
        camera.addComponent(cmpTransform);
        let cmpCamera = new ƒ.ComponentCamera();
        camera.addComponent(cmpCamera);
        viewPort = new ƒ.Viewport("MiniScene", node, cmpCamera);
        viewPort.drawScene();
        viewPort.showSceneGraph();
        console.group("Original");
        console.log(cmpTransform);
        console.groupEnd();
        console.group("Serialized");
        let serializer = new ƒ.Serializer();
        let serialization = serializer.serialize(cmpTransform);
        console.log(serialization);
        console.groupEnd();
        console.group("Stringified");
        let json = JSON.stringify(serialization);
        console.log(json);
        console.groupEnd();
        console.group("Parsed");
        serialization = JSON.parse(json);
        console.log(serialization);
        console.groupEnd();
        console.group("Reconstructed");
        let reconstruction = serializer.deserialize(serialization);
        console.log(reconstruction);
        console.groupEnd();
    }
    MiniScene.init = init;
})(MiniScene || (MiniScene = {}));
//# sourceMappingURL=MiniScene.js.map