name: Attach FUDGE Runtime to release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Create Zip File
        run: zip -r fudge.zip Core/Build/

      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fudge.zip
          asset_name: fudge.zip
          asset_content_type: application/zip       