name: Create FUDGE runtime

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Install dependencies
        run: npm install

      - name: Install TypeScript
        run: npm install typescript@4.6.0-beta

      - name: Build
        run: npx tsc --project Core/Source/tsconfig.json # Compile TypeScript files
      
      - name: Create runtime zip
        uses: actions/upload-artifact@v3
        with:
          name: fudge
          path: |
            # List the files and directories that you want to include in the artifact
            Core/Build/
